const menu = [
    {
      id: "1",
      cardNo: "1",
      mealCategory: "Breakfast",
      dishName: "Idali Sambar",
      image: "/images/Idali.jpg",
      dishPrice: "30RS",
      dishDescription: "Idali Sambar is very delicious and healthy dish, you must try it..",
    },
    {
      id: "2",
      cardNo: "2",
      mealCategory: "Breakfast",
      dishName: "MasalaDosa",
      image: "/images/MasalaDosa.jpg",
      dishPrice: "40RS",
      dishDescription: "Masala Dosa is a popular South Indian dish made from rice and lentils.",
    },
    {
      id: "3",
      cardNo: "3",
      mealCategory: "Lunch",
      dishName: "ButterChicken",
      image: "/images/ButterChicken.jpg",
      dishPrice: "150RS",
      dishDescription: "Butter Chicken is a rich and creamy chicken curry.",
    },
    {
      id: "4",
      cardNo: "4",
      mealCategory: "Lunch",
      dishName: "Pizza",
      image: "/images/Pizza.jpg",
      dishPrice: "120RS",
      dishDescription: "Veggie Pizza topped with a variety of fresh vegetables.",
    },
    {
      id: "5",
      cardNo: "5",
      mealCategory: "Dinner",
      dishName: "Sushi Platter",
      image: "/images/SushiPlatter.jpg",
      dishPrice: "180RS",
      dishDescription: "Sushi Platter with assorted sushi rolls and sashimi.",
    },
    {
      id: "6",
      cardNo: "6",
      mealCategory: "Dinner",
      dishName: "Paneer Tikka",
      image: "/images/PaneerTikka.jpg",
      dishPrice: "90RS",
      dishDescription: "Paneer Tikka is a popular Indian appetizer made with marinated cottage cheese.",
    },
    {
      id: "7",
      cardNo: "7",
      mealCategory: "Snacks",
      dishName: "French Fries",
      image: "/images/FrenchFries.jpg",
      dishPrice: "50RS",
      dishDescription: "Crispy and delicious French fries served with ketchup.",
    },
    {
      id: "8",
      cardNo: "8",
      mealCategory: "Snacks",
      dishName: "Nachos with Cheese",
      image: "/images/Nachos.jpg",
      dishPrice: "70RS",
      dishDescription: "Nachos served with melted cheese and jalapenos.",
    },
    {
      id: "9",
      cardNo: "9",
      mealCategory: "Dessert",
      dishName: "Chocolate Brownie",
      image: "/images/ChocolateBrownie.jpg",
      dishPrice: "60RS",
      dishDescription: "Decadent chocolate brownie served with a scoop of vanilla ice cream.",
    },
    {
      id: "10",
      cardNo: "10",
      mealCategory: "Dessert",
      dishName: "Fruit Salad",
      image: "/images/FruitSalad.jpg",
      dishPrice: "45RS",
      dishDescription: "Fresh fruit salad with a mix of seasonal fruits.",
    },
    {
      id: "11",
      cardNo: "11",
      mealCategory: "Dessert",
      dishName: "Fruit Salad",
      image: "/images/FruitSalad.jpg",
      dishPrice: "45RS",
      dishDescription: "Fresh fruit salad with a mix of seasonal fruits.",
    },
  ];
  
  export default menu;
  